# Generated by Django 5.0.6 on 2024-05-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originAccount', models.IntegerField()),
                ('iban', models.CharField(max_length=34)),
                ('description', models.CharField(max_length=254)),
                ('amount', models.FloatField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
