# Generated by Django 5.0.6 on 2024-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationaltransfer',
            name='originAccount',
            field=models.CharField(max_length=12),
        ),
    ]
